docs/data_model.md
python/gink/__init__.py
python/gink/impl/box.py
python/gink/impl/coding.py
python/gink/tests/test_box.py

Box data structure and tests are complete.
Note:
I changed the assertion at line 166 in coding.py because it was raising an assertion error when I tried to get the contents of the box. Not sure if that is intentional, but I commented it out and everything worked.
The box test for set and get currently fails because an integer is converted to a floating point. I left the test failing as-is, because you mentioned that was a bug.

Added Box data structure and tests. Fixed a few typos.

---

javascript/Dockerfile
javascript/implementation/builders.js
javascript/integration-tests/browser-client-test/browser-test.js
javascript/integration-tests/browser-client-test/remote-control.js
javascript/integration-tests/node-client-test.js
javascript/integration-tests/routing-server-test.js
javascript/package.json

Making a new pull request because I messed the other branch up really bad and this is probably the easiest way. We can delete the other PR once this is merged.

Char26 ts docker

---

javascript/implementation/Container.ts
javascript/implementation/IndexedDbStore.ts
javascript/implementation/PairMap.ts
javascript/implementation/PairSet.ts
javascript/implementation/Store.ts
javascript/unit-tests/PairMap.test.ts
javascript/unit-tests/PairSet.test.ts

Changed the types accepted by the pair data structures to support muids or containers interchangeably.

Char26 pairtypes

---

python/gink/impl/container.py
python/gink/impl/property.py
python/gink/tests/test_property.py

Cleaned up one of the things that wasn't quite finished from #26.
Changed property to clear itself and update using a single bundle based on the contents passed to the constructor (if applicable), rather than loop through each item in the contents.

Char26 property

---

javascript/implementation/Listener.ts
javascript/static/connections.html
javascript/static/create_connection.html
javascript/static/create_connection.js
javascript/static/get_connections.js
javascript/static/list_connections.html

The actual html that lists and creates connections.
#51

Char26 displayconnections

---

javascript/Dockerfile
javascript/implementation/CommandLineInterace.ts
javascript/implementation/Listener.ts
javascript/implementation/SimpleServer.ts
javascript/integration-tests/Expector.js
javascript/integration-tests/browser-client-test/remote-control.js
javascript/static/create_connection.html
javascript/static/create_connection.js
javascript/static/get_connections.js
javascript/static/list_connections.html

Added the endpoints for listing connections and creating new connections.
When a connection is created through the endpoint, the instance gets two greetings from two different(?) peers. I am not sure if there is a reason for this, or if it is a bug.
#50

Char26 connections

---

.readthedocs.yaml
python/docs/examples.md
python/docs/getting_started.md

readthedocs is breaking with automodules currently, since there is no build step to actually make the builders.

added fix to readthedocs.yaml to build the builders

---

.gitignore
.readthedocs.yaml
proto/entry.proto
python/gink/impl/builders.py
python/gink/impl/key_set.py
python/gink/impl/pair_map.py
python/gink/tests/test_key_set.py

I wasn't 100% sure on how to handle bytes in a formatted string (line 129 pair_map.py), so I am just dumping the raw version for now.

fixed the mypy errors that were hiding :)

---

.github/workflows/publish-npm.yml
.readthedocs.yaml
javascript/package.json

also removed a typo I didn't catch before :)

added action to publish to npm on release

---

.readthedocs.yaml
python/docs/getting_started.md
python/setup.py

finally got rtd to work

---

.github/workflows/typescript-docs.yml

the only thing actually changed here other than indentation is actions/artifact-upload@v1 from v3

changes to make typescript docs actually deploy to gh pages

---

.github/workflows/publish-npm.yml
.github/workflows/publish-pypi.yml
.github/workflows/typescript-docs.yml

Fixed some syntax and file path issues that will hopefully make these actions actually succeed. As you can see, I am in a war with GitHub actions and yml.

updated yml files to fix all of my bugs..

---

Dockerfile
Makefile
packages.txt

Due to the time this takes might not be worth added as a pre-submit check but good to have to run manually occasionally.

ensure that everything can be built and tested on Debian

---

javascript/implementation/Container.ts
javascript/implementation/IndexedDbStore.ts
javascript/implementation/factories.ts
javascript/unit-tests/Role.test.ts

My TypeScript formatter went a little crazy here. Let me know if it is polluting the PRs and I can turn it off.

swapped over to Array.isArray()

---

javascript/implementation/Role.ts
javascript/unit-tests/Role.test.ts

I still plan on adding an isExcluded method, but it is going to require a bit more work - so I wanted to get the first version of memory store out, then work on that.

changed contains to isIncluded and fixed bug in Role.ts

---

javascript/implementation/MemoryStore.ts
javascript/implementation/Role.ts
javascript/implementation/utils.ts
javascript/unit-tests/Box.test.ts
javascript/unit-tests/Directory.test.ts
javascript/unit-tests/GinkInstance.test.ts
javascript/unit-tests/KeySet.test.ts
javascript/unit-tests/MemoryStore.test.ts
javascript/unit-tests/PairMap.test.ts
javascript/unit-tests/PairSet.test.ts
javascript/unit-tests/Property.test.ts
javascript/unit-tests/Role.test.ts
javascript/unit-tests/Sequence.test.ts
javascript/unit-tests/factories.test.ts
javascript/unit-tests/pointingTo.test.ts
javascript/unit-tests/utils.test.ts

Decided to split this PR up - this one is mainly adding memory store to all tests, and a few fixes. The following PRs will be bug fixes to get the tests to pass.

some fixes and added memory store to tests

---

javascript/Dockerfile
javascript/implementation/GinkInstance.ts
javascript/implementation/IndexedDbStore.ts
javascript/integration-tests/Expector.js
javascript/integration-tests/dashboard.test.js
javascript/package.json

To test:
`make && make clean`
`npm run serve`
go to `localhost:8080`
The problem is line 260 in IndexedDbStore.ts.
Check the browser console for error message

transaction bug for browser

---

javascript/integration-tests/dashboard.test.js
javascript/static/dashboard/scripts/Page.js

this fully tests each page for a directory. I plan to eventually add another part where it navigates the pages of a sequence's entries.

updated dashboard test to use ui rather than javascript

---

javascript/implementation/IndexedDbStore.ts
javascript/implementation/MemoryStore.ts
javascript/implementation/Property.ts
javascript/unit-tests/Property.test.ts

purposely branched this off of dashboard-fixes because I want to use it in the next PR which will show contents of a property.

added getAll to property and added tests

---

javascript/static/dashboard/scripts/Database.js
javascript/static/dashboard/scripts/Page.js
javascript/static/dashboard/styles.css

To test:
`make clean && make`
`npm run serve`
go to `localhost:8080`
Rather than adding a button, I made the container's title have an onclick callback that lets you update the name. Not sure if that is the best way to do it, but it works for now!

added naming of containers

---

python/gink/__main__.py
python/gink/impl/connection.py
python/gink/impl/database.py
python/gink/impl/selectable_console.py

The current implementation is a bit rough around the edges but this probably is good enough for a demo.

integrated read eval print loop

---

javascript/implementation/MemoryStore.ts
javascript/implementation/utils.ts

Will be revisiting this eventually, but figured I'd get a temporary fix out for now.

added temporary fix for sequence moving in memory store

---

python/gink/impl/abstract_store.py
python/gink/impl/bundle_wrapper.py
python/gink/impl/database.py
python/gink/impl/lmdb_store.py
python/gink/impl/log_backed_store.py
python/gink/impl/memory_store.py
python/gink/tests/test_store.py

* Removing the outbox part of the store interface.
* Added a bundle wrapper class to allow the bundle info to be pre-computed before passing to `apply_bundle` 
* Added callback to be called when a bundle is actually added to the store

simplify store interface

---

python/gink/impl/abstract_store.py
python/gink/impl/database.py
python/gink/impl/lmdb_store.py
python/gink/impl/log_backed_store.py
python/gink/impl/watcher.py
python/gink/tests/test_database.py
python/gink/tests/test_logbackedstore.py

Arguably this should have been included in the prior PR, because otherwise the refresh doesn't help much.

(python) include the broadcast when getting a notification from the store

---

.github/workflows/macos-integration.yml
javascript/integration-tests/ts-py-test.js

For some reason localhost doesn’t work, but 0.0.0.0 does. 
Localhost was working locally, just not in the github runner.

ts->py test failed using localhost in github runner

---

javascript/implementation/Container.ts
javascript/implementation/Edge.ts
javascript/implementation/EdgeType.ts
javascript/implementation/IndexedDbStore.ts
javascript/implementation/MemoryStore.ts
javascript/implementation/PairMap.ts
javascript/implementation/PairSet.ts
javascript/implementation/Property.ts
javascript/implementation/Role.ts
javascript/implementation/Sequence.ts
javascript/implementation/typedefs.ts
javascript/implementation/utils.ts
javascript/unit-tests/PairMap.test.ts
javascript/unit-tests/PairSet.test.ts
javascript/unit-tests/Property.test.ts
javascript/unit-tests/graph.test.ts
proto/container.proto

Implement (re)ordering for edge entries, and also cleaned up the interface so that only Addressable is passed around rather than having to guess if something is a muid.

implemented reordering for edges

---

javascript/implementation/Addressable.ts
javascript/implementation/Container.ts
javascript/implementation/Directory.ts
javascript/implementation/Edge.ts
javascript/implementation/IndexedDbStore.ts
javascript/implementation/KeySet.ts
javascript/implementation/Keyed.ts
javascript/implementation/LogBackedStore.ts
javascript/implementation/MemoryStore.ts
javascript/implementation/PairMap.ts
javascript/implementation/Property.ts
javascript/implementation/Store.ts
javascript/implementation/factories.ts
javascript/implementation/store_utils.ts
javascript/implementation/typedefs.ts
javascript/implementation/utils.ts
javascript/unit-tests/Property.test.ts

Mostly merging the Directory, Property, and PairMap implementations into one generic class.

some refactoring

---

proto/behavior.proto
proto/muid.proto
python/gink/__init__.py
python/gink/impl/braid.py
python/gink/impl/builders.py
python/gink/impl/coding.py
python/gink/impl/container.py
python/gink/impl/database.py
python/gink/impl/lmdb_store.py
python/gink/impl/memory_store.py
python/gink/impl/muid.py
python/gink/impl/typedefs.py
python/gink/tests/test_braid.py
python/gink/tests/test_sequence.py

Mostly for internal use in the braid server.

braid container in python

---

.github/workflows/macos-integration.yml
javascript/integration-tests/authentication-test.js
javascript/integration-tests/chain-reuse-py-test.js
javascript/integration-tests/expector-test.js
javascript/integration-tests/node-client-test.js
javascript/integration-tests/spawn-test.js
javascript/integration-tests/wsgi-test.js
packages.txt
python/gink/impl/utilities.py
python/setup.py

A bunch of random changes to get the integration tests to pass on MacOS. 
Mostly this PR consists of changing a few more ports and changing shell/node location based on os.
Additionally, I am using psutil to determine if a process is still running, which wasn't implemented yet for Mac.

fix mac python chain reuse

---

javascript/implementation/Sequence.ts
javascript/unit-tests/Sequence.test.ts

Two questions:
Should the method be called `extend` ?
Should it return something? Maybe an iterable of Muids?

added list extend method

---

python/gink/impl/braid_server.py
python/gink/tests/test_braid_server.py

Allows for other database management data other than the braids themselves.

moved braids to be a sub-directory of the root directory

---

javascript/implementation/Database.ts
javascript/implementation/store_utils.ts

Added relativeTo context to to builderToMuid and removed unused variables

added context to builder

---

.github/workflows/macos-integration.yml
javascript/package-lock.json
python/setup.py

Also, setup.py was using an outdated version of protobuf. This was only being used on the Mac runner.

update npm dependencies to address security vulnerabilities

---

python/gink/impl/box.py
python/gink/impl/property.py
python/gink/tests/test_database.py

Going to do a followup PR to clean up some of the container constructors to make them all use ordered* and accept a string muid. 
This one gets the dump functionality mostly tested.
It may also be nice to have some sort of database.load() method

python data dumping

---

python/gink/impl/group.py
python/gink/tests/test_database.py

Let me know if this is a reasonable solution to group dumping/contents.

group from contents working

---

Dockerfile
python/gink/impl/coding.py
python/gink/impl/container.py
python/gink/impl/directory.py
python/gink/impl/group.py
python/gink/impl/key_set.py
python/gink/impl/typedefs.py
python/gink/tests/test_fuzz.py
python/setup.py

adjustments to type stuff to make typegurad happy

---

javascript/implementation/Bundler.ts
javascript/implementation/Decomposition.ts
javascript/implementation/MemoryStore.ts

Obviously there are other tests failing with this, but the directory test with the bytes key does work, so this may help figure out what is going on there.

directory test passes

---

python/gink/impl/abstract_store.py
python/gink/impl/coding.py
python/gink/impl/lmdb_store.py
python/gink/impl/memory_store.py
python/gink/tests/test_store.py

MemoryStore version will be coming in a different PR

drop history for LmdbStore

---

javascript/package-lock.json

Fix the 3 security vulnerabilities from the Elliptic dependency.

update package-lock with elliptic patch

---

javascript/package-lock.json
javascript/package.json

Somehow the actual prettier dependency didn't get added in my huge formatting PR. Lol

fix vulnerability and add prettier

---

javascript/implementation/Box.ts
javascript/implementation/Container.ts
javascript/implementation/Group.ts
javascript/implementation/KeySet.ts
javascript/implementation/Keyed.ts
javascript/implementation/PairSet.ts
javascript/implementation/Store.ts
javascript/implementation/utils.ts
javascript/package-lock.json
javascript/package.json
javascript/unit-tests/Box.test.ts
javascript/unit-tests/Directory.test.ts
javascript/unit-tests/Group.test.ts
javascript/unit-tests/KeySet.test.ts
javascript/unit-tests/Keyed.test.ts
javascript/unit-tests/PairSet.test.ts

This PR is for resetting keyed containers, minus Property.
Property will require a bit more work and it would pollute this PR.

TypeScript reset for Keyed containers

---

javascript/implementation/Edge.ts
javascript/implementation/EdgeType.ts
javascript/implementation/IndexedDbStore.ts
javascript/implementation/Sequence.ts
javascript/implementation/Store.ts
javascript/implementation/store_utils.ts
javascript/unit-tests/graph.test.ts

I think I did this this right... but there are a ton of things to consider when resetting properties, etc, so you may want to look at this PR extra critically.
(Full database reset in next PR)

reset EdgeType
