- .readthedocs.yaml
- python/gink/impl/coding.py
- python/gink/impl/lmdb_store.py
- python/gink/tests/test_database.py
Key Set now resets with Database.reset() (kind of).
I'm going to add an issue with this, but for some reason KeySet.get_global_instance() cannot be reset through Database.reset(), but a normal key set can now be reset.
to_last_with_prefix() is not finding the global keyset in the database.
This PR is also an excuse to fix my file path typo for the requirements.txt to build the docs :)
> non-global instance of key set resetting

- javascript/Dockerfile
- javascript/integration-tests/browser-client-test/browser.test.js
- javascript/karma.conf.js
- javascript/package.json
Still having trouble with browser unit tests specifically on my M1 mac. I'll keep playing around with that, but this should be a step forward. I left comments in the test files, but make sure to set env CHROME_BIN=/usr/bin/chrome or whatever your path to chrome/chromium is for the tests to run.
This also removes a bunch of bloat karma-launchers that we aren't using by removing the webpack-karma-jasmine package.
> browser tests working on rpi

- javascript/implementation/IndexedDbStore.ts
Inspects the call stack to limit reuse of transactions to matching use cases.
(Note: probably will not rely on the call-stack inspection in the future, this is just a temporary work around.)
> limit reuse of transactions

- javascript/Dockerfile
- javascript/implementation/IndexedDbStore.ts
- javascript/integration-tests/Expector.js
- javascript/integration-tests/dashboard.test.js
- javascript/package.json
Also, added a test that makes sure the server does not crash when the page refreshes.
To run the test that fails locally:
`npm run browser-integration`
> moved back to individual transactions for everything other than adding a bundle

- javascript/package.json
- javascript/tsconfig.json
- javascript/unit-tests/Sequence.test.ts
- Run unit tests against typescript rather than both TS and JS
- Added a small sleep timer between sequence moves in the Sequence.move test to ensure there is enough of a gap to actually move the items. It was slightly random before, based on how fast the runner would move them, so the test would fail occasionally.
- Don't type check library files, added to tsconfig.json
> fixing test issues

- javascript/integration-tests/py-ts-test.js
I have run the py-ts test about 15 times in the mac runner with this change and it has never failed, so I assume this is the solution to the unreliable test.
> added sleep to make test less flaky

- .dockerignore
- Dockerfile
- proto/change.proto
The `npm install` and `npm rebuild` commands take a long time, so it's best to make them dependent only on the package.json and run them before any commands that are dependent on files likely to change (I.e. the actual project code).
> rearrange dockerfile to make it slightly more effective at caching

- proto/muid.proto
- python/gink/impl/coding.py
- python/gink/impl/lmdb_store.py
- python/gink/impl/muid.py
- python/gink/tests/test_store.py
The graph reset algo will require relative offsets due to how the stream of changes needs to reference newly created entries.
> allow for relative offsets

- javascript/implementation/main.ts
This addresses issue #146 
Some "types" of disconnects/connection rejections would cause the server to crash. I'm not sure that this is the best overall solution, but this is far better than having the server crash on a closed connection.
> stop some unhandled websocket errors from crashing server

- .github/workflows/publish-npm.yml
- .github/workflows/publish-pypi.yml
- .github/workflows/typescript-docs.yml
We were creating a ton of versions in PyPI and npm, so this should cut down on the number of jobs for trivial commits, or commits irrelevant to ts/python.
> only publish package when specific files are changed

- javascript/implementation/Bundler.ts
- javascript/implementation/Database.ts
- javascript/implementation/Decomposition.ts
- javascript/implementation/IndexedDbStore.ts
- javascript/implementation/LogBackedStore.ts
- javascript/implementation/MemoryStore.ts
- javascript/implementation/Peer.ts
- javascript/implementation/Retrieval.ts
- javascript/implementation/Store.ts
- javascript/implementation/store_utils.ts
- javascript/implementation/typedefs.ts
- javascript/unit-tests/LogBackedStore.test.ts
- javascript/unit-tests/Store.test.ts
- javascript/unit-tests/test_utils.ts
The bundle view acts as a "partially digested" bundle that already has the bundle info computed for a particular bundle, rather that relying on the store to create it.
> refactor to use bundle view

- javascript/implementation/Bundler.ts
- javascript/implementation/Database.ts
- javascript/implementation/Decomposition.ts
- javascript/implementation/builders.d.ts
- javascript/implementation/builders.js
- javascript/unit-tests/LogBackedStore.test.ts
- javascript/unit-tests/Store.test.ts
- javascript/unit-tests/test_utils.ts
- proto/bundle.proto
- proto/header.proto
- python/gink/impl/builders.py
- python/gink/impl/bundle_info.py
- python/gink/impl/bundle_wrapper.py
- python/gink/impl/bundler.py
- python/gink/impl/database.py
- python/gink/impl/lmdb_store.py
- python/gink/tests/test_store.py
Previously all of the metadata fields were top level in the bundle proto.  This means that you might need to scan all of the bundle bytes to ensure that you had all of the header fields.  Shoving them all in a header makes it slightly easier to have a parser that can only read the header without trying to parse all of the remaining changes.
> move bundle metadata into a header to allow for header-only read

- python/gink/__main__.py
- python/gink/impl/abstract_store.py
- python/gink/impl/connection.py
- python/gink/impl/database.py
- python/gink/impl/listener.py
- python/gink/impl/looping.py
- python/gink/impl/selectable_console.py
- python/gink/impl/utilities.py
- python/gink/impl/websocket_connection.py
- python/gink/impl/wsgi_connection.py
- python/gink/impl/wsgi_listener.py
- python/gink/tests/test_database.py
- python/gink/tests/test_websocket_connection.py
- python/gink/tests/test_wsgi_server.py
In order to support the braid server (which will effectively require two databases running at the same time) I've pulled out the select loop from the database run method into a free standing `loop` utility function.  It takes something that implements a new `Selectable` protocol (interface), which has a `fileno` method and an `on_ready` method.  In order to facilitate the use case of listening sockets adding new connections, the `on_ready` is allowed to return more selectables to add to the loop.
> extract select loop from database.run into a separate function

- .gitignore
- Dockerfile
- javascript/package-lock.json
- Swapping from npm install to npm ci
[npm ci](https://docs.npmjs.com/cli/v7/commands/npm-ci) is designed for use in automated platforms (tests, docker, etc.) and is generally recommended over npm install. This uses the package-lock.json file, which is why that is added. 
It is possible this just isn't worth it or necessary, so let me know in that case.
- Remove the mv node_modules command
Let me know if I am missing something, but it seems like this command wasn't even necessary...?
> updates to dockerfile

- Dockerfile
There were a couple reasons why this wasn't working on the pi. One of which is chromium-browser doesn't exist for ARM, but the `chromium` package works on my pi and wsl/debian.
Feel free to pull this and try to build the image yourself. It is working on my Pi 5.
> edit dockerfile to run tests on raspberry pi

- javascript/implementation/index.ts
- javascript/implementation/main.ts
- javascript/package.json
I removed any exports that are not needed on the client side from the index.ts file. These exports happen in main.ts instead.
Part of what was happening was, when the user writes something like `import { Database } from "@x5e/gink"`, it would resolve the import to  @x5e/gink/tsc.out/implementation/main.js, which is really not ideal for the client side. By changing "main" in the package.json to `tsc.out/implementation/index.js`, referring to `@x5e/gink` while importing will resolve to `@x5e/gink/tsc.out/implementation/index.js`.
> fixed issue causing npm downloaded gink to break in browser

- .github/workflows/publish-npm.yml
Looks like we weren't installing any node modules in the npm publish action from when I changed to npm ci.
Also it was using a deprecated node version.
> fix npm publish action

- javascript/implementation/Database.ts
- javascript/unit-tests/Database.test.ts
I was previously looping through each change in a change map to create a list of containers, then sending the bundle info to the listeners subscribed to that container. That works, but for some reason I wasn't checking to see if there actually were any listeners... this will definitely speed something up.
Also fixed an issue where a container clearance wouldn't call the container specific listener.
> check for container in clearance and speed up receive bundle

- javascript/implementation/Database.ts
- javascript/integration-tests/remote-listener-test.js
- javascript/unit-tests/Database.test.ts
While working with gink on the demo, I found myself REALLY wanting a way to differentiate between local and remote commits. I figured out a workaround, but it isn't super pretty and I think this makes the interface much easier to use. The bundle listener will be a VERY commonly used feature, since applications will need to update accordingly when synchronizing between instances.
> bundle listeners can now be subscribed to only remote bundles

- javascript/implementation/Database.ts
- javascript/integration-tests/remote-listener-test.js
- javascript/unit-tests/Database.test.ts
This was something that stood out as an inconvenience while using gink. The use case I ran into was where I needed to detect if a change was from my own instance (same medallion). Here's how I did that before this change (maybe there is an easier way):
And heres now:
```ts
const chain = await db.getOrStartChain();
```
> explicitly start a chain

- javascript/integration-tests/authentication-test.js
- javascript/integration-tests/browser-client-test/browser.test.js
- javascript/integration-tests/browser_test_utilities.js
- javascript/integration-tests/chain-reuse-ts-test.js
- javascript/integration-tests/dashboard.test.js
- javascript/integration-tests/logbacked-peers-test.js
- javascript/integration-tests/node-client-test.js
- javascript/integration-tests/py-py-test.js
- javascript/integration-tests/py-ts-test.js
- javascript/integration-tests/remote-listener-test.js
- javascript/integration-tests/routing-server-test.js
- javascript/integration-tests/run_integration_tests.sh
- javascript/integration-tests/ts-py-test.js
- javascript/integration-tests/wsgi-test.js
I am hoping this also fixed a problem of the browser integration tests hanging on mac.
Also I don't really love how I did this, but I couldn't figure out a better way. If two tests are in the same file they will both use the same port number unless it is a constant in the file. Probably ok for now, definitely better than before.
> integration tests now use an increasing port number to ensure they don't overlap.

- python/gink/impl/braid_server.py
- python/gink/tests/test_braid_server.py
At some point we're going to need to support hosting multiple applications/accounts from the braid server.  The account ID might get passed in via the domain (e.g. wss://my-app.x5e.io/document).  In any case if someone starts hosting on their own then decides that they want to start using X5E hosting, we have to effectively merge their braid server control database with ours, so we can't use the global root as the basis for everything.
> get account root from box rather than using global root

- javascript/implementation/CommandLineInterface.ts
- javascript/implementation/Database.ts
- javascript/implementation/typedefs.ts
- javascript/integration-tests/browser-tests/client-side-script.js
- javascript/unit-tests/LogBackedStore.test.ts
If people are going to be listening for changes, it would make sense for them to easily be able to see what changes were made in a received bundle. That is still a little buried in the builder, but WAY more accessible like this.
> send bundle view instead of info to listeners

- python/gink/__main__.py
- python/gink/impl/addressable.py
- python/gink/impl/box.py
- python/gink/impl/braid.py
- python/gink/impl/container.py
- python/gink/impl/directory.py
- python/gink/impl/graph.py
- python/gink/impl/group.py
- python/gink/impl/key_set.py
- python/gink/impl/pair_map.py
- python/gink/impl/pair_set.py
- python/gink/impl/property.py
- python/gink/impl/sequence.py
- python/gink/tests/test_database.py
This cleans up  and standardizes the container constructors. Next step will be fuzz tests, but at least the database dumping seems to be mostly working.
> refactoring container/subclass constructors and fixing container dumps

- javascript/integration-tests/browser-tests/browser.test.js
- javascript/integration-tests/browser-tests/dashboard.test.js
- python/gink/tests/test_sequence.py
Made the dashboard test a bit less involved, but it still achieves the same thing. Added `jest.retryTimes` to retry the test twice if it fails. This should help make these browser tests less flaky.
> tweaks to browser tests

- javascript/implementation/IndexedDbStore.ts
- javascript/implementation/MemoryStore.ts
- javascript/unit-tests/Property.test.ts
- javascript/unit-tests/Store.test.ts
getContainersByName uses an index now in MemoryStore.
IndexedDbStore was not handling changed names correctly - the container would be forever found in getContainersByName for its old name.
> byName index for TypeScript MemoryStore and IDB byName fix

- .gitignore
- Makefile
- docs/development.md
- javascript/integration-tests/browser_test_utilities.js
- javascript/integration-tests/run_integration_tests.sh
- javascript/package.json
- python/requirements.txt
- python/setup.py
I realized we had no documentation for developers to actually build gink for local development. 
This was actually kind of a nightmare, primarily due to Python packages.
You may have noticed that I unpinned the mypy version we had pinned a while ago. This version of mypy is now impossible to install, at least in my testing through a fresh Debian docker container. It tries to compile a deprecated version of typed_ast that fails every time.
Additionally, using `pip3 install .[test]` through setup.py fails due to us bumping versions using ${VERSION} and sed in our workflows. ${VERSION} is not a valid version. To install this way, the developer would need to change the version to some version number before the install would work. I decided to add a requirements.txt with both necessary and dev …
> build and testing documentation

- javascript/implementation/Edge.ts
- javascript/implementation/EdgeType.ts
- javascript/implementation/Group.ts
- javascript/implementation/IndexedDbStore.ts
- javascript/implementation/KeySet.ts
- javascript/implementation/LogBackedStore.ts
- javascript/implementation/MemoryStore.ts
- javascript/implementation/PairSet.ts
- javascript/implementation/Sequence.ts
- javascript/implementation/Store.ts
- javascript/implementation/Vertex.ts
- javascript/implementation/builders.d.ts
- javascript/implementation/store_utils.ts
- javascript/implementation/typedefs.ts
- javascript/implementation/utils.ts
- javascript/unit-tests/Sequence.test.ts
- javascript/unit-tests/graph.test.ts
Something I need clarification on for all of this reset functionality:
For recursively resetting sub-containers, are we only talking about the containers that were there at toTime? Or are we resetting all containers there now as well?
I have been assuming we just reset the containers that were there at the time we are resetting to, rather than if a container is a current entry.
**I'm going to implement EdgeType reset in another PR since this one is getting lengthy**
> reset for sequence and vertex
